### ISSUE TITLE
Development environment error

### ISSUE THREAD

**Issue by othreecodes** [svub/whatsapp-rest-webservice#1]
can you please do a `pip freeze` of your virtualenv
i keep running into errors while trying to set this up. 
e.g 
```bash
    from django.core.handlers.wsgi import STATUS_CODE_TEXT
ImportError: cannot import name STATUS_CODE_TEXT
```

**Comment by teenoh** [comment]
Same here... Looks like it was developed with python2

**Comment by othreecodes** [comment]
Its python2. But a lot of dependencies are not highlighted in the setup instructions. I finally got it installed only for the messages to not deliver.
It shows "waiting for this message".

On Jul 15, 2017 14:24, teenoh <notifications@github.com> wrote:

Same here... Looks like it was developed with python2

**Comment by svub** [comment]
Hey, super sorry for the late response. I did not get any notifications about this issue.
It was a one week quick hack any feedback welcome. 
If you like, send pull requests with all the changes you need to get it going.
One big part of making it work is to register you phone number and not having WhatsApp running on it at the same time. So in the company we ended up using a phone that had no WhatsApp installed.
Yes, it's Python 2 and I'm new to it.

**Comment by svub** [comment]
Did a `pip freeze` and added `requirements.txt` to the repo.
I hope it's still helpful, let me know.
